### ISSUE TITLE
how to set auto reset

### ISSUE THREAD

**Issue by Spyplayz13** [StrangeOne101/PlatinumArenas#11]

**Comment by StrangeOne101** [comment]
There is no current way to do this with the plugin alone. You'll need to use other timer plugins or your if your host supports schedules, use that to run commands.

The issue for timers being added can be followed in #9

**Comment by Spyplayz13** [comment]
> There is no current way to do this with the plugin alone. You'll need to use other timer plugins or your if your host supports schedules, use that to run commands.
> 
> The issue for timers being added can be followed in #9

can suggest any timer plugin

**Comment by StrangeOne101** [comment]
> can suggest any timer plugin

https://www.spigotmc.org/resources/command-timer.24141/
