### ISSUE TITLE
UPDATE TO 1.21+❗❗❗❗

### ISSUE THREAD

**Issue by pinoynodes** [StrangeOne101/PlatinumArenas#18]
please make it compatible with 1.21 version

**Comment by notjoshx** [comment]
yes

**Comment by KEVINIIE123** [comment]
yes

**Comment by AkaTriggered** [comment]
**Hey @notjoshx i have made an update for this plugin you can find it out through this link https://github.com/AkaTriggered/BetterArenaResetter**

**Comment by StrangeOne101** [comment]
> **Hey @notjoshx i have made an update for this plugin you can find it out through this link https://github.com/AkaTriggered/BetterArenaResetter**

For future reference, PRs were welcome and would have been accepted

**Comment by StrangeOne101** [comment]
Closed due to completed
