### ISSUE TITLE
update to 1.21

### ISSUE THREAD

**Issue by katleal** [StrangeOne101/PlatinumArenas#20]
update it to 1.21 please, this is the best plugin for regenerating arenas, ty

**Comment by IndJitesh** [comment]
yes you should update it this plugin is verry good

**Comment by AkaTriggered** [comment]
**Made an Update For This Plugin https://github.com/AkaTriggered/BetterArenaResetter**

**Comment by StrangeOne101** [comment]
Closed due to completed
