### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/io/filefilter/SuffixFileFilter

### ISSUE THREAD

**Issue by archroot** [StrangeOne101/PlatinumArenas#6]
![image](https://user-images.githubusercontent.com/41123605/174761941-4ca599c4-ba66-4cb6-8d0f-3215bb7f71ad.png)

**Comment by StrangeOne101** [comment]
Odd. Thanks for the report. I'll look into this

I know it isn't a 1.16 issue specifically because I did test on 1.16. Current thought is the class might be included with WorldEdit, and that's why all my tests have been fine

**Comment by StrangeOne101** [comment]
@archroot Can you please check if the issue is fixed in https://github.com/StrangeOne101/PlatinumArenas/releases/tag/v0.7.3-TEST ?

**Comment by archroot** [comment]
Problem solved!
